name: Build

on: [push, workflow_dispatch]
  inputs:
    environment:
      description: 'Which environment to deploy to'
      required: true
      default: 'staging'
      type: string
      options:
        - staging
        - production
    dataset:
      description: 'Which dataset to use'
      required: false
      deafult: 'small'
      type: string
      options:
        - small
        - large

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Building .."

  test-setup:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      testmo-run-id: ${{ steps.run-tests.outputs.testmo-run-id }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci

      # Optionally add a couple of fields such as the git hash and link to the build
      - run: |
          npx testmo automation:resources:add-field --name git --type string \
            --value ${GITHUB_SHA:0:7} --resources resources.json
          RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          npx testmo automation:resources:add-link --name build \
            --url $RUN_URL --resources resources.json

      # Check if the required variables are available
      - run: |
          if [[ -z "${TESTMO_URL}" ]]; then
            echo "The TESTMO_URL secret is not defined for this repository"
            exit 1
          fi

          if [[ -z "${TESTMO_TOKEN}" ]]; then
            echo "The TESTMO_TOKEN secret is not defined for this repository"
            exit 1
          fi
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

      # Create test run
      - run: |
          npx testmo automation:run:create \
            --instance "$TESTMO_URL" \
            --project-id 5 \
            --name "Parallel mocha test run" \
            --resources resources.json \
            --source "unit-tests" > testmo-run-id.txt
          ID=$(cat testmo-run-id.txt)
          echo "testmo-run-id=$ID" >> $GITHUB_OUTPUT
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
        id: run-tests

  test:
    needs: test-setup
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ci_index: [0, 1, 2, 3]
        ci_total: [4]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 19
          cache: npm
      - run: npm ci

      # Run automated tests and report results to Testmo
      - run: |
          npx testmo automation:run:submit-thread \
            --instance "$TESTMO_URL" \
            --run-id "${{ needs.test-setup.outputs.testmo-run-id }}" \
            --results results/*.xml \
            -- npm run mocha-junit-parallel # Note space after --
        env:
          CI_TOTAL: ${{ matrix.ci_total }}
          CI_INDEX: ${{ matrix.ci_index }}
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

  test-complete:
    needs: [test-setup, test]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci

      # Mark test run completed
      - run: |
          npx testmo automation:run:complete \
            --instance "$TESTMO_URL" \
            --run-id "${{ needs.test-setup.outputs.testmo-run-id }}"
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

  deploy:
    needs: [test, test-complete]
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Deploying to ${{ github.event.inputs.environment }} environment"
          echo "Using ${{ github.event.inputs.dataset }} dataset"
